### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
vector = np.random.rand(10)
matrix = np.array([[11, 14, 17], [20, 23, 26], [29, 32, 35]])
print(matrix, vector)

[[11 14 17]
 [20 23 26]
 [29 32 35]] [0.94474621 0.91458796 0.86719621 0.1516524  0.25348533 0.33132222
 0.74601298 0.58525588 0.04567975 0.43533908]



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [8]:
CONST = 10
vector_plus_const = vector + CONST
vector_plus_const = np.round(vector_plus_const, 2)
matrix_mul_const = matrix * CONST
new_square_vector = np.square(vector)
print(matrix_mul_const, vector_plus_const, new_square_vector)



[[110 140 170]
 [200 230 260]
 [290 320 350]] [10.94 10.91 10.87 10.15 10.25 10.33 10.75 10.59 10.05 10.44] [0.89254541 0.83647113 0.75202927 0.02299845 0.06425481 0.10977442
 0.55653537 0.34252445 0.00208664 0.18952011]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [15]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [18]:
result_matrix = np.dot(A, B)
display(result_matrix)

# матриці result та С не можна помножити бо у них різна розмірність
# аналогічно з пунктом 3 



array([[0.232 , 0.1627, 0.2145],
       [0.3061, 0.4867, 0.633 ],
       [0.1393, 0.2261, 0.294 ]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [22]:
result_matrix_transponent = result_matrix.T
vector_transponent = vector.T
column_vector = np.expand_dims(vector, axis=1)
# display(vector, column_vector)
column_vector_t = column_vector.T
display(vector, column_vector)
display(column_vector_t, column_vector_t.shape)

array([0.94474621, 0.91458796, 0.86719621, 0.1516524 , 0.25348533,
       0.33132222, 0.74601298, 0.58525588, 0.04567975, 0.43533908])

array([[0.94474621],
       [0.91458796],
       [0.86719621],
       [0.1516524 ],
       [0.25348533],
       [0.33132222],
       [0.74601298],
       [0.58525588],
       [0.04567975],
       [0.43533908]])

array([[0.94474621, 0.91458796, 0.86719621, 0.1516524 , 0.25348533,
        0.33132222, 0.74601298, 0.58525588, 0.04567975, 0.43533908]])

(1, 10)